Documentation work
ometman/Admission-trials pull request #1
Opened 2022-12-12 20:56 UTC by ometman

I have used the documentation template of freecodeacademy to create a documentation site. It has the index, style.css, readme, license, js.index and index.babel files.

2022-12-12 21:09 UTC, ometman commented on index.html
> +  <section class="main-section" id="Introduction">
Your code has so many ids. one or two is okay for a page.  Many ids can create problems for managing styles in one place

2022-12-12 21:09 UTC, ometman commented on index.html
> +  <section class="main-section" id="Javascript_and_Java">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:09 UTC, ometman commented on index.html
> +  <section class="main-section" id="Hello_world">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:10 UTC, ometman commented on index.html
> +  <section class="main-section" id="Declaring_variables">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:10 UTC, ometman commented on index.html
> +   <section class="main-section" id="Variables_scope">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:10 UTC, ometman commented on index.html
> +  <section class="main-section" id="Reference">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:11 UTC, ometman commented on index.html
> +   <section class="main-section" id="Function_declaration">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:12 UTC, ometman commented on index.html
> +   <section class="main-section" id="while_statements">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:12 UTC, ometman commented on index.html
> +   <section class="main-section" id="if...else_statements">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:12 UTC, ometman commented on index.html
> +   <section class="main-section" id="Data_types">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:13 UTC, ometman commented on index.html
> +   <section class="main-section" id="Constants">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:13 UTC, ometman commented on index.html
> +   <section class="main-section" id="Global_variables">
Your code has so many ids. one or two is okay for a page. Many ids can create problems for managing styles in one place

2022-12-12 21:15 UTC, ometman commented on index.html
> +  <title> </title>
The title should not be empty.  It is part of semantic rules. A title helps search engines to people to know what your page is about.

2022-12-12 21:17 UTC, ometman commented on index.html
> +    <header> JS Documentation </header>
The header has no style class. If you have others pages where header changes it will be difficult to manage.

2022-12-12 21:19 UTC, ometman commented on index.html
> +    </header>
You have another header.  This is not a good semantic practice. One is okay for effective style management.

2022-12-12 21:20 UTC, ometman commented on index.html
> +    </header>
You have another header. This is not a good semantic practice. One is okay for effective style management.

2022-12-12 21:21 UTC, ometman commented on index.html
> +    </header>
You have another header. This is not a good semantic practice. One is okay for effective style management.

2022-12-12 21:22 UTC, ometman commented on index.html
> +    <header>
You have another header. This is not a good semantic practice. One is okay for effective style management.

2022-12-12 21:23 UTC, ometman commented on index.html
> +    </header>
You have another header. This is not a good semantic practice. One is okay for effective style management.

2022-12-12 23:16 UTC, GedeonTS commented on index.html
> +  <section class="main-section" id="Introduction">
- [ ] :thinking: I think it would be better if you give your comments as suggestions, not orders, I suggest starting your sentences with something like " I think...",  "Kindly...", or "In my opinion...".

2022-12-12 23:17 UTC, GedeonTS commented on index.html
> +  <section class="main-section" id="Javascript_and_Java">
- [ ] :thinking: just like I like above, I think it would be better if you give your comments as suggestions, not orders, I suggest starting your sentences with something like " I think...",  "Kindly...", or "In my opinion...". :recycle:

2022-12-12 23:34 UTC, GedeonTS commented on index.html
> +  <section class="main-section" id="Hello_world">
- [ ] Good job giving the reason for comments, however, just like I like above, thinking:  I think it would be better if you give your comments as suggestions, not orders, I suggest starting your sentences with something like " I think...",  "Kindly...",  "In my opinion..." or some other cool things you may know. :recycle:

2022-12-12 23:36 UTC, GedeonTS commented on index.html
> +  <section class="main-section" id="Declaring_variables">
- [ ] Good job giving the reason for comments, however, just like I like above, thinking:  I think it would be better if you give your comments as suggestions, not orders, I suggest starting your sentences with something like " I think...",  "Kindly...",  "In my opinion..." or some other cool things you may know. :recycle:

2022-12-12 23:38 UTC, GedeonTS commented on index.html
> +    </header>
- [ ] Good job giving the reason for comments, however, just like I like above, thinking:  I think it would be better if you give your comments as suggestions, not orders, instead of "This is not a good semantic practice" I suggest starting your sentences with something like " I think...",  "Kindly...",  "In my opinion..." or some other cool things you may know. :recycle:

2022-12-12 23:47 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @ometman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- Good use of the Github review feature :+1: 
- Good use of inline comments :+1: 
- Good job, giving the reason of all your comments :+1: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- [ ] I think it would be better if you use more emojis in your comments because this will make your review more human friendly :clap: 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 01:20 UTC, ometman reviewed
Hi @ometman ,

Good Work So Far!!! 👏

[https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966]


### Highlights

✅  Good commit history 👌 
✅ Linters test passed 💯 
✅ Html and CSS  semantics is good 👏 👏 
✅ Github flows is good 👍  👍 


### Required Changes
There are still some very few things you need to fix, as in the comments below.


[Optional] Kindly consider fixing the following:
1. I suggest you use one or two headers and  style Ids in your html.
2. Kindly add  a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) and customize it to your project.

_Optional suggestions 🤷‍♂️
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Important Notes 📝
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-12-13 01:48 UTC, rskinnerc requested changes
Hi @ometman 👋👋👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/26911718/207204786-fc98b1cd-e4bf-4eb1-822f-1826e9031e37.gif)


 ## Highlights
- You are using GitHub's CR features! Awesome! 🤪
- Well done, you left some inline comments!

 ## Required Changes ♻️
_Check the comments under the review._
♻️♻️ You did a good job updating some of your comments as the previous reviewer suggested ✌️✌️. However, there are a few things you can work on so your future code reviews will encourage people to improve. Please check under one of your comments. 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 01:48 UTC, rskinnerc commented on index.html
> +  <section class="main-section" id="Introduction">
♻️ Good job adding some more kindness to your requirement. However, most of the time people feel more encouraged and willing to accept criticism when it sounds friendly. I would suggest you rephrase your comments to something more polite and along the way, you could even let the dev know the good things she/he did. For example:

_Great job using the `main` tag as the main content container of your page 👌. However, please note that seems like there are too many `ids` in your HTML. I'd suggest adding `id` to the elements that actually would need it. For example, when working with CSS or Javascript. Kindly review which of those could be removed 🙏🙏_

2022-12-13 09:42 UTC, ometman reviewed
Hi @ometman ,

Good Work So Far!!! 👏



Highlights
✅ Good commit history 👌
✅ Linters test passed 💯
✅ Html and CSS semantics is good 👏 👏
✅ Github flows is good 👍 👍

Required Changes
There are still some very few things you need to fix, as in the comments below.

[Optional] Kindly consider fixing the following:

I suggest you use one or two headers and style Ids in your html.
Kindly add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) and customize it to your project.
Optional suggestions 🤷‍♂️
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Important Notes 📝
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-12-13 09:51 UTC, Olamarx approved these changes
Hi @ometman,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>
## Highlights
- Polite comments ✔️
- Reason for changes ✔️
- GitHub review features ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 11:10 UTC, merged

2023-01-16 09:32 UTC, GedeonTS commented
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @ometman ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- Good use of the Github review feature :clap: 
- Polite suggestions :clap: 
- Good use of inline reviews :clap: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._